name: Deploy Node Js App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            cd /var/www/backend/
            git pull origin main
            npm install
            npm run build
            cp /var/www/backend/.env /var/www/backend/build/.env
            cp /var/www/backend/.env /var/www/backend/build/app/.env
            cp /var/www/backend/private.key /var/www/backend/build/
            cp  /var/www/backend/public.key /var/www/backend/build/
            pm2 restart all 
